# Generated by Django 5.0.4 on 2024-04-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('imageUrl', models.URLField()),
                ('ratingUrl', models.URLField()),
                ('carbody', models.CharField(max_length=100)),
            ],
        ),
    ]
